#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gesti√≥n de Bases de Datos 2025-26
description: Apuntes y recursos para la asignatura de GBD del IES Miguel Herrero 2025-26
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
